### ISSUE TITLE
Nhibernate and Dapper Implementation

### ISSUE THREAD

**Issue by muratyuceer** [lelong37/URF#16]
Hi
Do you have ready Nhibernate and Dapper Implementation example

**Comment by lelong37** [comment]
We don't, all our interfaces are here: https://github.com/lelong37/URF/tree/master/main/Source/Repository.Pattern, so that if one needed to implement another  ORM/technology should be trivial, should be no more than 10 or so interfaces that need to be implemented. If you do go down that road, please let us know, would love a PR on this.

**Comment by muratyuceer** [comment]
Hi thanks for answer,

i dont wanna use ServiceLocator. must i use ServiceLocator?

        public IRepository<TEntity> Repository<TEntity>() where TEntity : class, ITrackable
        {
            if (ServiceLocator.IsLocationProviderSet)
            {
                return ServiceLocator.Current.GetInstance<IRepository<TEntity>>();
            }

            return RepositoryAsync<TEntity>();
        }

________________________________
Gönderen: Long Le <notifications@github.com>
Gönderildi: 19 Ekim 2017 Perşembe 21:30
Kime: lelong37/URF
Bilgi: muratyuceer; Author
Konu: Re: [lelong37/URF] Nhibernate and Dapper Implementation (#16)


We don't, all our interfaces are here: https://github.com/lelong37/URF/tree/master/main/Source/Repository.Pattern, so that if one needed to implement another ORM/technology should be trivial, should be no more than 10 or so interfaces that need to be implemented. If you do go down that road, please let us know, would love a PR on this.
